version: "2"

services:
  web:
    build: .
    image: "${JOB_BASE_NAME}_api"
    container_name: "${JOB_BASE_NAME}_web"
    expose:
      - "80"
    restart: always
    environment:
      - VIRTUAL_HOST=${WEB_URL}