version: "2"

services:
  api:
    build: .
    image: "${JOB_BASE_NAME}_api"
    container_name: "${JOB_BASE_NAME}_api"
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: always
    command: [ "npm", "start" ]

networks:
  default:
    external:
      name: database