api:
  image: "${JOB_BASE_NAME}_api"
  container_name: "${JOB_BASE_NAME}_api"
  build: .
  ports:
    - "${API_PORT}:${API_PORT}"
  external_links:
    - mongo:mongodb
  restart: always
  command: [ "npm", "start" ]