api:
  build: .
  expose:
    - "${API_PORT}"
  external_links:
    - mongo:mongodb
  container_name: "${JOB_BASE_NAME}_api"
  restart: always
  command: [ "npm", "start" ]
  
  environment:
    - VIRTUAL_HOST=dev.marcoplaats.maarten.co.uk
    - VIRTUAL_PORT=8080